---

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - atom
        - neofetch
        - darktable
        - tmux
